# https://docs.docker.com/compose/compose-file/
name: foundationx

services:
    db:
        image: postgres

        ports:
            - ${DB_PORT}

        volumes:
            - data:/data/db

        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}

    api:
        build: .
        env_file: .env
        ports:
            - ${API_PORT}
        restart: ${RESTART_POLICY}
        mem_limit: ${HARD_MEMORY_LIMIT}
        mem_reservation: ${SOFT_MEMORY_LIMIT}
volumes:
    data: {}
